version: '3.4'

networks:
  app:

services:
  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - app
      
  python-api:
    build:
      context: apps/python-api/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - database
    networks:
      - app
